version: '3.3'

services:
  record_keeper:
    build: "."
    image: "record_keeper:discord"
    restart: unless-stopped
    volumes: 
      - "./database/:/app/database/"
      - "./config/:/app/config/"
